/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../studio/schema.json
export type Cta = {
  href: string
  buttonText: string
  newTab?: boolean
}

export type ImageAndAltText = {
  image?: ImageAndAltTextImage
  altText?: string
}

export type Card = {
  cardTitle: string
  cardSubtitle?: string
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Cta2 = {
  href: string
  buttonText: string
  newTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageAndAltTextImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CtaWithMediaCardImageAndAltText = {
  image?: ImageAndAltTextImage
  altText?: string
}

export type Expanded = {
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  bgImage?: BgImage
  icon?: Icon
  cta?: Cta
}

export type BgImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "bgImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Collapsed = {
  name?: string
  bgImage?: CollapsedBgImage
  icon?: CollapsedIcon
}

export type CollapsedBgImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "collapsed.bgImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CollapsedIcon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "collapsed.icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectCta = {
  label?: string
  href?: string
}

export type Calendar = {
  _type: 'calendar'
  title?: string
  iframeUrl?: string
}

export type CardGrid = {
  _type: 'cardGrid'
  heading?: string
  subtitle?: string
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    cta?: Cta
    fullWidth?: boolean
    _key: string
  }>
  removePaddingTop?: boolean
}

export type TwoCtasWithImage = {
  _type: 'twoCtasWithImage'
  title: string
  emphasizedText?: string
  textColor?: 'black' | 'dark-blue' | 'medium-blue'
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  ctas?: Array<{
    description?: string
    href: string
    buttonText: string
    newTab?: boolean
    _type: 'ctaWithDescription'
    _key: string
  }>
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type CtaWithCard = {
  _type: 'ctaWithCard'
  title: string
  emphasizedText?: string
  textColor?: 'black' | 'dark-blue' | 'medium-blue'
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  overlapImage?: boolean
  ctas?: Array<{
    href: string
    buttonText: string
    newTab?: boolean
    _type: 'cta'
    _key: string
  }>
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  icon?: boolean
}

export type CtaWithMediaCard = {
  _type: 'ctaWithMediaCard'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: CtaWithMediaCardImageAndAltText
  cta?: Cta
  video?: string
}

export type IntroBlade = {
  _type: 'introBlade'
  titles?: Array<{
    title: string
    _key: string
  }>
  blurb?: string
  ctas?: Array<{
    buttonText: string
    link: string
    _key: string
  }>
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Leadership = {
  _type: 'leadership'
  title: string
  people?: Array<{
    imageAndAltText?: ImageAndAltText
    name: string
    role: string
    _key: string
  }>
}

export type NumberedList = {
  _type: 'numberedList'
  title: string
  items?: Array<{
    number?: number
    heading: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _key: string
  }>
}

export type OneColInfo = {
  _type: 'oneColInfo'
  variant: 'text' | 'image'
  title: string
  bodyContent?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  imageAndAltText?: ImageAndAltText
  imageBlurb?: string
}

export type FourColStatistics = {
  _type: 'fourColStatistics'
  sideTitle?: string
  sideBlurb?: string
  stats?: Array<{
    number: string
    label: string
    _key: string
  }>
}

export type StatisticsTwoCol = {
  _type: 'statisticsTwoCol'
  title: string
  stats?: Array<{
    number: string
    label: string
    imageAndAltText?: ImageAndAltText
    _key: string
  }>
}

export type ClubCards = {
  _type: 'clubCards'
  title: string
  subtitle?: string
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    cta?: Cta
    _key: string
  }>
}

export type ThreeColCards = {
  _type: 'threeColCards'
  cards?: Array<{
    title: string
    imageAndAltText?: ImageAndAltText
    href: string
    _key: string
  }>
}

export type ThreeColCircleImage = {
  _type: 'threeColCircleImage'
  title: string
  columns?: Array<{
    name: string
    blurb?: string
    imageAndAltText?: ImageAndAltText
    _key: string
  }>
}

export type ThreeColCtas = {
  _type: 'threeColCtas'
  cards?: Array<{
    title: string
    description?: string
    href: string
    _key: string
  }>
}

export type ThreeColEventCards = {
  _type: 'threeColEventCards'
  heading?: string
  bgTexture?: boolean
  cards?: Array<{
    title: string
    imageAndAltText?: ImageAndAltText
    subtitle?: string
    body?: string
    cta?: ObjectCta
    _key: string
  }>
}

export type ThreeColExpandingCards = {
  _type: 'threeColExpandingCards'
  heading: string
  subtitle?: string
  footnote?: string
  arrowLabel?: string
  sectionBgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  items?: Array<{
    expanded?: Expanded
    collapsed?: Collapsed
    _key: string
  }>
}

export type ThreeColToggle = {
  _type: 'threeColToggle'
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    _key: string
  }>
  removePaddingTop?: boolean
}

export type TwoColBulletsWithCTAs = {
  _type: 'twoColBulletsWithCTAs'
  title: string
  leftBullets?: Array<{
    text: string
    _key: string
  }>
  rightBullets?: Array<{
    text: string
    _key: string
  }>
  cta?: Cta
  cta2?: Cta2
  showIcon?: boolean
}

export type TwoColInfoWithCard = {
  _type: 'twoColInfoWithCard'
  heading: string
  subtitle?: string
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  bg?: 'white' | 'dark-blue'
  photoSide?: 'left' | 'right'
}

export type TwoColInfoWithImage = {
  _type: 'twoColInfoWithImage'
  variant?: 'with-borders' | 'without-borders'
  bgColor?: 'white' | 'dark-blue'
  title?: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  card?: Card
}

export type TwoColInfo = {
  _type: 'twoColInfo'
  title: string
  headerBlurb?: string
  items?: Array<{
    title: string
    subtitle?: string
    detail?: string
    _key: string
  }>
}

export type ImageWithText = {
  _type: 'imageWithText'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
}

export type TextWithLogo = {
  _type: 'textWithLogo'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type TitleAndSubtitle = {
  _type: 'titleAndSubtitle'
  titleOne: string
  titleTwo?: string
}

export type Subnav = {
  _type: 'subnav'
  ctas?: Array<{
    href: string
    buttonText: string
    newTab?: boolean
    _key: string
  }>
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type EventReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'event'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'event'
  href?: string
  page?: PageReference
  event?: EventReference
  openInNewTab?: boolean
}

export type HeroBanner = {
  _type: 'heroBanner'
  titleOne: string
  titleTwo?: string
  cta?: Cta
  imageAndAltText?: ImageAndAltText
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'event'
        href?: string
        page?: PageReference
        event?: EventReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'event'
      href?: string
      page?: PageReference
      event?: EventReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  eventType?: 'athleticEvent' | 'academicEvent' | 'otherEvent'
  dateText?: string
  time?: string
  place?: string
  description?: BlockContent
  featured?: boolean
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  title?: string
  role?: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & Subnav)
    | ({
        _key: string
      } & TitleAndSubtitle)
    | ({
        _key: string
      } & TextWithLogo)
    | ({
        _key: string
      } & ImageWithText)
    | ({
        _key: string
      } & TwoColInfo)
    | ({
        _key: string
      } & TwoColInfoWithImage)
    | ({
        _key: string
      } & TwoColInfoWithCard)
    | ({
        _key: string
      } & TwoColBulletsWithCTAs)
    | ({
        _key: string
      } & ThreeColToggle)
    | ({
        _key: string
      } & ThreeColExpandingCards)
    | ({
        _key: string
      } & ThreeColEventCards)
    | ({
        _key: string
      } & ThreeColCtas)
    | ({
        _key: string
      } & ThreeColCircleImage)
    | ({
        _key: string
      } & ThreeColCards)
    | ({
        _key: string
      } & ClubCards)
    | ({
        _key: string
      } & StatisticsTwoCol)
    | ({
        _key: string
      } & FourColStatistics)
    | ({
        _key: string
      } & OneColInfo)
    | ({
        _key: string
      } & NumberedList)
    | ({
        _key: string
      } & Leadership)
    | ({
        _key: string
      } & IntroBlade)
    | ({
        _key: string
      } & CtaWithMediaCard)
    | ({
        _key: string
      } & CtaWithCard)
    | ({
        _key: string
      } & TwoCtasWithImage)
    | ({
        _key: string
      } & CardGrid)
    | ({
        _key: string
      } & Calendar)
  >
  metaTitle?: string
  metaDescription: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ogDescription?: string
  robots?: 'index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow'
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Cta
  | ImageAndAltText
  | Card
  | Cta2
  | SanityImageAssetReference
  | ImageAndAltTextImage
  | CtaWithMediaCardImageAndAltText
  | Expanded
  | BgImage
  | Icon
  | Collapsed
  | CollapsedBgImage
  | CollapsedIcon
  | ObjectCta
  | Calendar
  | CardGrid
  | TwoCtasWithImage
  | CtaWithCard
  | CtaWithMediaCard
  | IntroBlade
  | Leadership
  | NumberedList
  | OneColInfo
  | FourColStatistics
  | StatisticsTwoCol
  | ClubCards
  | ThreeColCards
  | ThreeColCircleImage
  | ThreeColCtas
  | ThreeColEventCards
  | ThreeColExpandingCards
  | ThreeColToggle
  | TwoColBulletsWithCTAs
  | TwoColInfoWithCard
  | TwoColInfoWithImage
  | TwoColInfo
  | ImageWithText
  | TextWithLogo
  | TitleAndSubtitle
  | Subnav
  | PageReference
  | EventReference
  | Link
  | HeroBanner
  | InfoSection
  | BlockContent
  | BlockContentTextOnly
  | Button
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | PersonReference
  | Event
  | Person
  | Slug
  | Page
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'event' | 'href' | 'page'
      href?: string
      page?: PageReference
      event?: EventReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    metaTitle,    metaDescription,    ogImage,    ogDescription,    robots,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "event": event->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "event": event->slug.current  }          }        }      },      _type == "heroBanner" => {        titleOne,        titleTwo,        cta,        imageAndAltText      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: null
  subheading: null
  metaTitle: string | null
  metaDescription: string
  ogImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  ogDescription: string | null
  robots: 'index, follow' | 'index, nofollow' | 'noindex, follow' | 'noindex, nofollow' | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'calendar'
        title?: string
        iframeUrl?: string
      }
    | {
        _key: string
        _type: 'cardGrid'
        heading?: string
        subtitle?: string
        cards?: Array<{
          title: string
          description?: string
          imageAndAltText?: ImageAndAltText
          cta?: Cta
          fullWidth?: boolean
          _key: string
        }>
        removePaddingTop?: boolean
      }
    | {
        _key: string
        _type: 'clubCards'
        title: string
        subtitle?: string
        cards?: Array<{
          title: string
          description?: string
          imageAndAltText?: ImageAndAltText
          cta?: Cta
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'ctaWithCard'
        title: string
        emphasizedText?: string
        textColor?: 'black' | 'dark-blue' | 'medium-blue'
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: ImageAndAltText
        overlapImage?: boolean
        ctas?: Array<{
          href: string
          buttonText: string
          newTab?: boolean
          _type: 'cta'
          _key: string
        }>
        bgImage?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        icon?: boolean
      }
    | {
        _key: string
        _type: 'ctaWithMediaCard'
        title: string
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: CtaWithMediaCardImageAndAltText
        cta?: Cta
        video?: string
      }
    | {
        _key: string
        _type: 'fourColStatistics'
        sideTitle?: string
        sideBlurb?: string
        stats?: Array<{
          number: string
          label: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'heroBanner'
        titleOne: string
        titleTwo: string | null
        cta: Cta | null
        imageAndAltText: ImageAndAltText | null
      }
    | {
        _key: string
        _type: 'imageWithText'
        title: string
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: ImageAndAltText
      }
    | {
        _key: string
        _type: 'introBlade'
        titles?: Array<{
          title: string
          _key: string
        }>
        blurb?: string
        ctas?: Array<{
          buttonText: string
          link: string
          _key: string
        }>
        bgImage?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'leadership'
        title: string
        people?: Array<{
          imageAndAltText?: ImageAndAltText
          name: string
          role: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'numberedList'
        title: string
        items?: Array<{
          number?: number
          heading: string
          body?: Array<{
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
            listItem?: 'bullet' | 'number'
            markDefs?: Array<{
              href?: string
              _type: 'link'
              _key: string
            }>
            level?: number
            _type: 'block'
            _key: string
          }>
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'oneColInfo'
        variant: 'image' | 'text'
        title: string
        bodyContent?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        imageAndAltText?: ImageAndAltText
        imageBlurb?: string
      }
    | {
        _key: string
        _type: 'statisticsTwoCol'
        title: string
        stats?: Array<{
          number: string
          label: string
          imageAndAltText?: ImageAndAltText
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'subnav'
        ctas?: Array<{
          href: string
          buttonText: string
          newTab?: boolean
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'textWithLogo'
        title: string
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColCards'
        cards?: Array<{
          title: string
          imageAndAltText?: ImageAndAltText
          href: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColCircleImage'
        title: string
        columns?: Array<{
          name: string
          blurb?: string
          imageAndAltText?: ImageAndAltText
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColCtas'
        cards?: Array<{
          title: string
          description?: string
          href: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColEventCards'
        heading?: string
        bgTexture?: boolean
        cards?: Array<{
          title: string
          imageAndAltText?: ImageAndAltText
          subtitle?: string
          body?: string
          cta?: ObjectCta
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColExpandingCards'
        heading: string
        subtitle?: string
        footnote?: string
        arrowLabel?: string
        sectionBgImage?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        items?: Array<{
          expanded?: Expanded
          collapsed?: Collapsed
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'threeColToggle'
        cards?: Array<{
          title: string
          description?: string
          imageAndAltText?: ImageAndAltText
          _key: string
        }>
        removePaddingTop?: boolean
      }
    | {
        _key: string
        _type: 'titleAndSubtitle'
        titleOne: string
        titleTwo?: string
      }
    | {
        _key: string
        _type: 'twoColBulletsWithCTAs'
        title: string
        leftBullets?: Array<{
          text: string
          _key: string
        }>
        rightBullets?: Array<{
          text: string
          _key: string
        }>
        cta?: Cta
        cta2?: Cta2
        showIcon?: boolean
      }
    | {
        _key: string
        _type: 'twoColInfo'
        title: string
        headerBlurb?: string
        items?: Array<{
          title: string
          subtitle?: string
          detail?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'twoColInfoWithCard'
        heading: string
        subtitle?: string
        bio?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: ImageAndAltText
        bg?: 'dark-blue' | 'white'
        photoSide?: 'left' | 'right'
      }
    | {
        _key: string
        _type: 'twoColInfoWithImage'
        variant?: 'with-borders' | 'without-borders'
        bgColor?: 'dark-blue' | 'white'
        title?: string
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: ImageAndAltText
        card?: Card
      }
    | {
        _key: string
        _type: 'twoCtasWithImage'
        title: string
        emphasizedText?: string
        textColor?: 'black' | 'dark-blue' | 'medium-blue'
        blurb?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        imageAndAltText?: ImageAndAltText
        ctas?: Array<{
          description?: string
          href: string
          buttonText: string
          newTab?: boolean
          _type: 'ctaWithDescription'
          _key: string
        }>
        bgImage?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "event" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'event'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allEventsQuery
// Query: *[_type == "event" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllEventsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: moreEventsQuery
// Query: *[_type == "event" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MoreEventsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: eventQuery
// Query: *[_type == "event" && slug.current == $slug] [0] {    description[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "event": event->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type EventQueryResult = {
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'event' | 'href' | 'page'
          href?: string
          page: string | null
          event: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: eventPagesSlugs
// Query: *[_type == "event" && defined(slug.current)]  {"slug": slug.current}
export type EventPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    metaTitle,\n    metaDescription,\n    ogImage,\n    ogDescription,\n    robots,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "event": event->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "event": event->slug.current\n  }\n\n          }\n        }\n      },\n      _type == "heroBanner" => {\n        titleOne,\n        titleTwo,\n        cta,\n        imageAndAltText\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "event" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "event" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllEventsQueryResult
    '\n  *[_type == "event" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MoreEventsQueryResult
    '\n  *[_type == "event" && slug.current == $slug] [0] {\n    description[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "event": event->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': EventQueryResult
    '\n  *[_type == "event" && defined(slug.current)]\n  {"slug": slug.current}\n': EventPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
  }
}
