/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Cta = {
  href: string
  buttonText: string
  newTab?: boolean
}

export type ImageAndAltText = {
  image?: ImageAndAltTextImage
  altText?: string
}

export type Card = {
  cardTitle: string
  cardSubtitle?: string
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Cta2 = {
  href: string
  buttonText: string
  newTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageAndAltTextImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CtaWithMediaCardImageAndAltText = {
  image?: ImageAndAltTextImage
  altText?: string
}

export type Expanded = {
  name?: string
  tagline?: string
  description?: string
  bgImage?: BgImage
  icon?: Icon
  cta?: ExpandedCta
}

export type BgImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "bgImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ExpandedCta = {
  label?: string
  href?: string
}

export type Collapsed = {
  name?: string
  bgImage?: CollapsedBgImage
  icon?: CollapsedIcon
  cta?: CollapsedCta
}

export type CollapsedBgImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "collapsed.bgImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CollapsedIcon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "collapsed.icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CollapsedCta = {
  label?: string
  href?: string
}

export type ObjectCta = {
  label?: string
  href?: string
}

export type Calendar = {
  _type: 'calendar'
  title?: string
  iframeUrl?: string
}

export type CardGrid = {
  _type: 'cardGrid'
  heading?: string
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    href: string
    fullWidth?: boolean
    _key: string
  }>
}

export type CtaWithCard = {
  _type: 'ctaWithCard'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  cta?: Cta
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  icon?: boolean
}

export type CtaWithMediaCard = {
  _type: 'ctaWithMediaCard'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: CtaWithMediaCardImageAndAltText
  cta?: Cta
  video?: string
}

export type IntroBlade = {
  _type: 'introBlade'
  titles?: Array<{
    title: string
    _key: string
  }>
  blurb?: string
  ctas?: Array<{
    buttonText: string
    link: string
    _key: string
  }>
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Leadership = {
  _type: 'leadership'
  title: string
  people?: Array<{
    imageAndAltText?: ImageAndAltText
    name: string
    role: string
    _key: string
  }>
}

export type NumberedList = {
  _type: 'numberedList'
  title: string
  items?: Array<{
    number?: number
    heading: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _key: string
  }>
}

export type OneColInfo = {
  _type: 'oneColInfo'
  variant: 'text' | 'image'
  title: string
  bodyContent?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  imageAndAltText?: ImageAndAltText
  imageBlurb?: string
}

export type FourColStatistics = {
  _type: 'fourColStatistics'
  sideTitle?: string
  sideBlurb?: string
  stats?: Array<{
    number: string
    label: string
    _key: string
  }>
}

export type StatisticsTwoCol = {
  _type: 'statisticsTwoCol'
  title: string
  stats?: Array<{
    number: string
    label: string
    _key: string
  }>
}

export type ThreeColCardsTall = {
  _type: 'threeColCardsTall'
  title: string
  subtitle?: string
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    cta?: Cta
    _key: string
  }>
}

export type ThreeColCards = {
  _type: 'threeColCards'
  cards?: Array<{
    title: string
    imageAndAltText?: ImageAndAltText
    href: string
    _key: string
  }>
}

export type ThreeColCircleImage = {
  _type: 'threeColCircleImage'
  title: string
  columns?: Array<{
    name: string
    blurb?: string
    imageAndAltText?: ImageAndAltText
    _key: string
  }>
}

export type ThreeColCtas = {
  _type: 'threeColCtas'
  cards?: Array<{
    title: string
    description?: string
    href: string
    _key: string
  }>
}

export type ThreeColEventCards = {
  _type: 'threeColEventCards'
  heading?: string
  bgTexture?: boolean
  cards?: Array<{
    title: string
    imageAndAltText?: ImageAndAltText
    subtitle?: string
    body?: string
    cta?: ObjectCta
    _key: string
  }>
}

export type ThreeColExpandingCards = {
  _type: 'threeColExpandingCards'
  heading: string
  subtitle?: string
  footnote?: string
  arrowLabel?: string
  sectionBgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  items?: Array<{
    expanded?: Expanded
    collapsed?: Collapsed
    _key: string
  }>
}

export type ThreeColToggle = {
  _type: 'threeColToggle'
  cards?: Array<{
    title: string
    description?: string
    imageAndAltText?: ImageAndAltText
    _key: string
  }>
}

export type TwoColBulletsWithCTAs = {
  _type: 'twoColBulletsWithCTAs'
  title: string
  leftBullets?: Array<{
    text: string
    _key: string
  }>
  rightBullets?: Array<{
    text: string
    _key: string
  }>
  cta?: Cta
  cta2?: Cta2
  showIcon?: boolean
}

export type TwoColInfoWithCard = {
  _type: 'twoColInfoWithCard'
  heading: string
  subtitle?: string
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  bg?: 'white' | 'dark-blue'
  photoSide?: 'left' | 'right'
}

export type TwoColInfoWithImage = {
  _type: 'twoColInfoWithImage'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
  card?: Card
}

export type TwoColInfo = {
  _type: 'twoColInfo'
  title: string
  headerBlurb?: string
  items?: Array<{
    title: string
    subtitle?: string
    detail?: string
    _key: string
  }>
}

export type ImageWithText = {
  _type: 'imageWithText'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  imageAndAltText?: ImageAndAltText
}

export type TextWithLogo = {
  _type: 'textWithLogo'
  title: string
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type TitleAndSubtitle = {
  _type: 'titleAndSubtitle'
  titleOne: string
  titleTwo?: string
}

export type Subnav = {
  _type: 'subnav'
  ctas?: Array<{
    href: string
    buttonText: string
    newTab?: boolean
    _key: string
  }>
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type EventReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'event'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'event'
  href?: string
  page?: PageReference
  event?: EventReference
  openInNewTab?: boolean
}

export type HeroBanner = {
  _type: 'heroBanner'
  titleOne: string
  titleTwo?: string
  cta?: Cta
  imageAndAltText?: ImageAndAltText
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'event'
        href?: string
        page?: PageReference
        event?: EventReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  title?: string
  role?: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'event'
      href?: string
      page?: PageReference
      event?: EventReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  eventType?: 'athleticEvent' | 'academicEvent' | 'otherEvent'
  dateText?: string
  time?: string
  place?: string
  description?: BlockContent
  featured?: boolean
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & Subnav)
    | ({
        _key: string
      } & TitleAndSubtitle)
    | ({
        _key: string
      } & TextWithLogo)
    | ({
        _key: string
      } & ImageWithText)
    | ({
        _key: string
      } & TwoColInfo)
    | ({
        _key: string
      } & TwoColInfoWithImage)
    | ({
        _key: string
      } & TwoColInfoWithCard)
    | ({
        _key: string
      } & TwoColBulletsWithCTAs)
    | ({
        _key: string
      } & ThreeColToggle)
    | ({
        _key: string
      } & ThreeColExpandingCards)
    | ({
        _key: string
      } & ThreeColEventCards)
    | ({
        _key: string
      } & ThreeColCtas)
    | ({
        _key: string
      } & ThreeColCircleImage)
    | ({
        _key: string
      } & ThreeColCards)
    | ({
        _key: string
      } & ThreeColCardsTall)
    | ({
        _key: string
      } & StatisticsTwoCol)
    | ({
        _key: string
      } & FourColStatistics)
    | ({
        _key: string
      } & OneColInfo)
    | ({
        _key: string
      } & NumberedList)
    | ({
        _key: string
      } & Leadership)
    | ({
        _key: string
      } & IntroBlade)
    | ({
        _key: string
      } & CtaWithMediaCard)
    | ({
        _key: string
      } & CtaWithCard)
    | ({
        _key: string
      } & CardGrid)
    | ({
        _key: string
      } & Calendar)
  >
  metaTitle?: string
  metaDescription: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ogDescription?: string
  robots?: 'index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow'
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Cta
  | ImageAndAltText
  | Card
  | Cta2
  | SanityImageAssetReference
  | ImageAndAltTextImage
  | CtaWithMediaCardImageAndAltText
  | Expanded
  | BgImage
  | Icon
  | ExpandedCta
  | Collapsed
  | CollapsedBgImage
  | CollapsedIcon
  | CollapsedCta
  | ObjectCta
  | Calendar
  | CardGrid
  | CtaWithCard
  | CtaWithMediaCard
  | IntroBlade
  | Leadership
  | NumberedList
  | OneColInfo
  | FourColStatistics
  | StatisticsTwoCol
  | ThreeColCardsTall
  | ThreeColCards
  | ThreeColCircleImage
  | ThreeColCtas
  | ThreeColEventCards
  | ThreeColExpandingCards
  | ThreeColToggle
  | TwoColBulletsWithCTAs
  | TwoColInfoWithCard
  | TwoColInfoWithImage
  | TwoColInfo
  | ImageWithText
  | TextWithLogo
  | TitleAndSubtitle
  | Subnav
  | PageReference
  | EventReference
  | Link
  | HeroBanner
  | InfoSection
  | BlockContent
  | BlockContentTextOnly
  | Button
  | Person
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Event
  | Slug
  | Page
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
