import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center p-4">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/contact">Academics</Link>
          <Link href="/about">Early Education</Link>
          <Link href="/blog">Elementary School</Link>
          <Link href="/portfolio">Middle School</Link>
          <Link href="/services">Student Life</Link>
          <Link href="/testimonials">Family Home</Link>
          <Link href="/contact">Clubs</Link>
          <Link href="/about">Athletics</Link>
          <Link href="/blog">Admissions</Link>
          <Link href="/blog">Tuition</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
